// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YmmoAPI.Data;

#nullable disable

namespace YmmoAPI.Migrations
{
    [DbContext(typeof(YmmoDbContext))]
    [Migration("20260312141106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YmmoAPI.Models.Agence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstSiege")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Agences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "25 Cours Mirabeau",
                            CodePostal = "13100",
                            EstSiege = true,
                            Nom = "Ymmo Siège - Aix-en-Provence",
                            Ville = "Aix-en-Provence"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "45 Avenue des Champs-Élysées",
                            CodePostal = "75008",
                            EstSiege = false,
                            Nom = "Ymmo Paris",
                            Ville = "Paris"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "12 Place Bellecour",
                            CodePostal = "69002",
                            EstSiege = false,
                            Nom = "Ymmo Lyon",
                            Ville = "Lyon"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "8 Quai du Port",
                            CodePostal = "13002",
                            EstSiege = false,
                            Nom = "Ymmo Marseille",
                            Ville = "Marseille"
                        },
                        new
                        {
                            Id = 5,
                            Adresse = "3 Place du Capitole",
                            CodePostal = "31000",
                            EstSiege = false,
                            Nom = "Ymmo Toulouse",
                            Ville = "Toulouse"
                        },
                        new
                        {
                            Id = 6,
                            Adresse = "15 Place de la Bourse",
                            CodePostal = "33000",
                            EstSiege = false,
                            Nom = "Ymmo Bordeaux",
                            Ville = "Bordeaux"
                        },
                        new
                        {
                            Id = 7,
                            Adresse = "20 Promenade des Anglais",
                            CodePostal = "06000",
                            EstSiege = false,
                            Nom = "Ymmo Nice",
                            Ville = "Nice"
                        },
                        new
                        {
                            Id = 8,
                            Adresse = "5 Place Royale",
                            CodePostal = "44000",
                            EstSiege = false,
                            Nom = "Ymmo Nantes",
                            Ville = "Nantes"
                        },
                        new
                        {
                            Id = 9,
                            Adresse = "10 Place Kléber",
                            CodePostal = "67000",
                            EstSiege = false,
                            Nom = "Ymmo Strasbourg",
                            Ville = "Strasbourg"
                        },
                        new
                        {
                            Id = 10,
                            Adresse = "7 Place de la Comédie",
                            CodePostal = "34000",
                            EstSiege = false,
                            Nom = "Ymmo Montpellier",
                            Ville = "Montpellier"
                        },
                        new
                        {
                            Id = 11,
                            Adresse = "22 Grand Place",
                            CodePostal = "59000",
                            EstSiege = false,
                            Nom = "Ymmo Lille",
                            Ville = "Lille"
                        },
                        new
                        {
                            Id = 12,
                            Adresse = "18 Place de la Mairie",
                            CodePostal = "35000",
                            EstSiege = false,
                            Nom = "Ymmo Rennes",
                            Ville = "Rennes"
                        },
                        new
                        {
                            Id = 13,
                            Adresse = "4 Place Victor Hugo",
                            CodePostal = "38000",
                            EstSiege = false,
                            Nom = "Ymmo Grenoble",
                            Ville = "Grenoble"
                        });
                });

            modelBuilder.Entity("YmmoAPI.Models.Annonce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BienId")
                        .HasColumnType("integer");

                    b.Property<int>("CreateurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BienId");

                    b.HasIndex("CreateurId");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("YmmoAPI.Models.Bien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("AgenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnneeConstruction")
                        .HasColumnType("integer");

                    b.Property<bool>("Ascenseur")
                        .HasColumnType("boolean");

                    b.Property<bool>("Balcon")
                        .HasColumnType("boolean");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DPE")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<bool>("Jardin")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("NbChambres")
                        .HasColumnType("integer");

                    b.Property<int>("NbPieces")
                        .HasColumnType("integer");

                    b.Property<bool>("Parking")
                        .HasColumnType("boolean");

                    b.Property<bool>("Piscine")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<double>("Surface")
                        .HasColumnType("double precision");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.HasIndex("AgentId");

                    b.ToTable("Biens");
                });

            modelBuilder.Entity("YmmoAPI.Models.PhotoBien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BienId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstPrincipale")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BienId");

                    b.ToTable("PhotosBien");
                });

            modelBuilder.Entity("YmmoAPI.Models.RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("BienId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BienId");

                    b.HasIndex("ClientId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("YmmoAPI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcheteurId")
                        .HasColumnType("integer");

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("BienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinalisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontantFinal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("VendeurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcheteurId");

                    b.HasIndex("AgentId");

                    b.HasIndex("BienId");

                    b.HasIndex("VendeurId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("YmmoAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgenceId = 1,
                            DateCreation = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ymmo.fr",
                            MotDePasseHash = "$2a$11$3aupF6LGPRaualWaA/UAiuSB/EmDkUou1xuhCTzEMMp0w4mKY.f5u",
                            Nom = "Admin",
                            Prenom = "Ymmo",
                            Role = 3
                        });
                });

            modelBuilder.Entity("YmmoAPI.Models.Annonce", b =>
                {
                    b.HasOne("YmmoAPI.Models.Bien", "Bien")
                        .WithMany("Annonces")
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Utilisateur", "Createur")
                        .WithMany("Annonces")
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("YmmoAPI.Models.Bien", b =>
                {
                    b.HasOne("YmmoAPI.Models.Agence", "Agence")
                        .WithMany("Biens")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Utilisateur", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agence");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("YmmoAPI.Models.PhotoBien", b =>
                {
                    b.HasOne("YmmoAPI.Models.Bien", "Bien")
                        .WithMany("Photos")
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bien");
                });

            modelBuilder.Entity("YmmoAPI.Models.RendezVous", b =>
                {
                    b.HasOne("YmmoAPI.Models.Utilisateur", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Bien", "Bien")
                        .WithMany()
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Utilisateur", "Client")
                        .WithMany("RendezVous")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Bien");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YmmoAPI.Models.Transaction", b =>
                {
                    b.HasOne("YmmoAPI.Models.Utilisateur", "Acheteur")
                        .WithMany("TransactionsAcheteur")
                        .HasForeignKey("AcheteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Utilisateur", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YmmoAPI.Models.Bien", "Bien")
                        .WithMany()
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YmmoAPI.Models.Utilisateur", "Vendeur")
                        .WithMany("TransactionsVendeur")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acheteur");

                    b.Navigation("Agent");

                    b.Navigation("Bien");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("YmmoAPI.Models.Utilisateur", b =>
                {
                    b.HasOne("YmmoAPI.Models.Agence", "Agence")
                        .WithMany("Agents")
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agence");
                });

            modelBuilder.Entity("YmmoAPI.Models.Agence", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Biens");
                });

            modelBuilder.Entity("YmmoAPI.Models.Bien", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("YmmoAPI.Models.Utilisateur", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("RendezVous");

                    b.Navigation("TransactionsAcheteur");

                    b.Navigation("TransactionsVendeur");
                });
#pragma warning restore 612, 618
        }
    }
}
